@host = http://localhost:3000/api
@createdInvestmentId = {{createdInvestment.response.body.$.id}}
@categoryPosId = {{categoryPos.response.body.$.id}}
@categoryIpcaId = {{categoryIpca.response.body.$.id}}
@createdUserId = {{createdUser.response.body.$.id}}
@token = {{signin.response.body.$.token}}
@userId = {{userMe.response.body.$.id}}

### Create User

# @name createdUser
POST {{host}}/users
Content-Type: application/json

{
  "name": "Luiz",
  "email": "luizcarlos@email.com",
  "password": "12345678"
}

### Signin 401

# @name signin
POST {{host}}/signin
Content-Type: application/json

{
  "email": "luizcarlos@email.com",
  "password": "321"
}

### Signin Ok

# @name signin
POST {{host}}/signin
Content-Type: application/json

{
  "email": "luizcarlos@email.com",
  "password": "12345678"
}

### Read User (whitout token)

GET {{host}}/users/me

### Read User (with token)

# @name userMe
GET {{host}}/users/me
Authorization: bearer {{token}}

### Create Image (User)

POST {{host}}/users/image
Authorization: bearer {{token}}
Content-Type: multipart/form-data; boundary="boundary"

--boundary
Content-Disposition: form-data; name="userId"

{{createdUserId}}
--boundary
Content-Disposition: form-data; name="image"; filename="avatar.png"
Content-Type: image/png

< ./public/imgs/profile/avatar.png
--boundary--

### Update Image (User)

PUT {{host}}/users/image
Authorization: bearer {{token}}
Content-Type: multipart/form-data; boundary="boundary"

--boundary
Content-Disposition: form-data; name="userId"

{{userId}}
--boundary
Content-Disposition: form-data; name="image"; filename="avatar.png"
Content-Type: image/png

< ./public/imgs/profile/avatar.png
--boundary--

### Read Categories

GET {{host}}/categories
Authorization: bearer {{token}}

### Read Categories by Name

# @name categoryPos
GET {{host}}/categories?name=Pós
Authorization: bearer {{token}}

### Read Categories by Name

# @name categoryIpca
GET {{host}}/categories?name=IPCA
Authorization: bearer {{token}}

### Create Investment

# @name createdInvestment
POST {{host}}/investments
Content-Type: application/json
Authorization: bearer {{token}}

{
  "name": "Tesouro Selic 2029",
  "value": 10000,
  "interest": "100% Selic",
  "createdAt": "2023-09-01",
  "broker": "Banco Inter",
  "categoryId": "{{categoryIpcaId}}",
  "userId": "{{createdUserId}}"
}

### Create Investment without value

POST {{host}}/investments
Content-Type: application/json
Authorization: bearer {{token}}

{
  "name": "Tesouro Selic 2029"
}

### Create Investment without investment values

POST {{host}}/investments
Authorization: bearer {{token}}

### Read Investments

GET {{host}}/investments
Authorization: bearer {{token}}

### Read Investments by id

GET {{host}}/investments/{{createdInvestmentId}}
Authorization: bearer {{token}}

### Read Investments with invalid id

GET {{host}}/investments/a
Authorization: bearer {{token}}

### Read Investments by Name

GET {{host}}/investments?name=Selic
Authorization: bearer {{token}}

### Update Investment

PUT {{host}}/investments/{{createdInvestmentId}}
Content-Type: application/json
Authorization: bearer {{token}}

{
  "name": "Tesouro Selic 2029",
  "value": 20000,
  "interest": "100% Selic",
  "createdAt": "2023-09-01",
  "broker": "Banco Inter",
  "categoryId": "{{categoryPosId}}",
  "userId": "{{createdUserId}}"
}

### Update Investment without value

PUT {{host}}/investments/{{createdInvestmentId}}
Content-Type: application/json
Authorization: bearer {{token}}

{
  "name": "Tesouro Selic 2029"
}

### Update Investment with invalid id

PUT {{host}}/investments/a
Content-Type: application/json
Authorization: bearer {{token}}

{
  "name": "Tesouro Selic 2029",
  "value": 25000
}

### Delete Investment

DELETE {{host}}/investments/{{createdInvestmentId}}
Authorization: bearer {{token}}

### Delete Investment with invalid id

DELETE {{host}}/investments/a
Authorization: bearer {{token}}
