@host = http://localhost:3000/api
@createdInvestmentId = {{createdInvestment.response.body.$.id}}
@categoryPosId = {{categoryPos.response.body.$.id}}
@categoryIpcaId = {{categoryIpca.response.body.$.id}}

### Read Categories

GET {{host}}/categories

### Read Categories by Name

# @name categoryPos
GET {{host}}/categories?name=Pós

### Read Categories by Name

# @name categoryIpca
GET {{host}}/categories?name=IPCA

### Create Investment

# @name createdInvestment
POST {{host}}/investments
Content-Type: application/json

{
  "name": "Tesouro Selic 2029",
  "value": 10000,
  "interest": "100% Selic",
  "createdAt": "2023-09-01",
  "broker": "Banco Inter",
  "categoryId": "{{categoryIpcaId}}"
}

### Create Investment without value

POST {{host}}/investments
Content-Type: application/json

{
  "name": "Tesouro Selic 2029"
}

### Create Investment without investment values

POST {{host}}/investments

### Read Investments

GET {{host}}/investments

### Read Investments by id

GET {{host}}/investments/{{createdInvestmentId}}

### Read Investments with invalid id

GET {{host}}/investments/a

### Read Investments by Name

GET {{host}}/investments?name=Selic

### Update Investment

PUT {{host}}/investments/{{createdInvestmentId}}
Content-Type: application/json

{
  "name": "Tesouro Selic 2029",
  "value": 20000,
  "interest": "100% Selic",
  "createdAt": "2023-09-01",
  "broker": "Banco Inter",
  "categoryId": "{{categoryPosId}}"
}

### Update Investment without value

PUT {{host}}/investments/{{createdInvestmentId}}
Content-Type: application/json

{
  "name": "Tesouro Selic 2029"
}

### Update Investment with invalid id

PUT {{host}}/investments/a
Content-Type: application/json

{
  "name": "Tesouro Selic 2029",
  "value": 25000
}

### Delete Investment

DELETE {{host}}/investments/{{createdInvestmentId}}

### Delete Investment with invalid id

DELETE {{host}}/investments/a
